spring:
  profiles:
    active: server
    include: oauth
  config:
    domain: ${{ http://localhost:8080/ }}
#    domain: ${{ secrets.AWS_S3_Endpoint }}

---
spring:
  config:
    activate:
      on-profile: local
---
spring:
  config:
    activate:
      on-profile: server