spring:
  profiles:
    active: local
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: ${{ secrets.GOOGLE_CLIENT_ID }}
            clientSecret: ${{ secrets.GOOGLE_CLIENT_SECRET }}
            redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - email
              - profile
          naver:
            client-id: ${{ secrets.NAVER_CLIENT_ID }}
            client-secret: ${{ secrets.NAVER_CLIENT_SECRET }}
            scope: name,email,profile_image
            redirect_uri: '{baseUrl}/{action}/oauth2/code/{registrationId}'
            authorization_grant_type: authorization_code
            client-name: Naver

            provider:
              naver:
                authorization_uri: https://nid.naver.com/oauth2.0/authorize
                token_uri: https://nid.naver.com/oauth2.0/token
                user-info-uri: https://openapi.naver.com/v1/nid/me
                user_name_attribute: response
          kakao:
            client-id: ${{ secrets.KAKAO_CLIENT_ID }}
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            client-authentication-method: POST
            client-secret: ${{ secrets.KAKAO_CLIENT_SECRET }}
            authorization-grant-type: authorization_code
            scope:
              - profile_nickname
              - profile_image
              - account_email
              - gender
              - birthday
            client_name: kakao
            provider:
              kakao:
                authorization-uri: https://kauth.kakao.com/oauth/authorize
                token-uri: https://kauth.kakao.com/oauth/token
                user-info-uri: https://kapi.kakao.com/v2/user/me
                user-name-attribute: id
---
spring:
  config:
    activate:
      on-profile: local
---
spring:
  config:
    activate:
      on-profile: server