name: JavaScript CI for Client

on:
  push:
    paths: [ 'client/**' ]
    branches: [ 'main' ]
  pull_request:
    paths: [ 'client/**' ]
    branches: [ "main" ]
    
env:
  S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}

defaults:
  run:
    working-directory: client # The working directory path

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.17.1]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    
    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Npm install
      run: npm install
    
    - name: Build
      run: npm run build

    # build한 후 프로젝트를 압축합니다.
    - name: Make zip file
      run: zip -r ./client.zip .
      shell: bash
    
    # Access Key와 Secret Access Key를 통해 권한을 확인합니다.
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-2
    
    # 압축한 프로젝트를 S3로 전송합니다.
    - name: Upload to S3
      run: aws s3 cp --region ap-northeast-2 ./client.zip s3://$S3_BUCKET_NAME/client.zip
